name: tensorflow
channels:
  - defaults
dependencies:
  - apscheduler=3.7.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.4.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.1.0
  - boto3=1.18.21
  - botocore=1.21.41
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.0.3
  - cryptography=36.0.0
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.4.1
  - flask=2.0.2
  - fonttools=4.25.0
  - freetype=2.11.0
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.3
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  - intel-openmp=2021.4.0
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - itsdangerous=2.0.1
  - jedi=0.18.1
  - jinja2=3.0.2
  - jmespath=0.10.0
  - joblib=1.1.0
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=7.1.0
  - jupyter_console=6.4.0
  - jupyter_core=4.9.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - lcms2=2.12
  - libffi=3.3
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  - libxslt=1.1.34
  - lxml=4.7.1
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclient=0.5.3
  - nbconvert=6.3.0
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - notebook=6.4.6
  - numexpr=2.8.1
  - numpy-base=1.21.2
  - olefile=0.46
  - openssl=1.1.1m
  - packaging=21.3
  - pandas=1.3.5
  - pandas-datareader=0.10.0
  - pandocfilters=1.4.3
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.4
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.10.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - pytz=2021.3
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qt=5.9.7
  - qtconsole=5.1.1
  - qtpy=1.10.0
  - readline=8.1.2
  - requests=2.27.1
  - s3transfer=0.5.0
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - send2trash=1.8.0
  - setuptools=58.0.4
  - sip=4.19.8
  - sqlite=3.37.0
  - terminado=0.9.4
  - testpath=0.5.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.1
  - tzlocal=2.0.0
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.2
  - wheel=0.37.1
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==0.15.0
    - astunparse==1.6.3
    - bayesian-optimization==1.2.0
    - cachetools==5.0.0
    - cloudpickle==2.0.0
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth==2.5.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - gunicorn==20.1.0
    - gym==0.21.0
    - h5py==2.10.0
    - kaggle==1.5.12
    - keras==2.7.0
    - keras-preprocessing==1.1.2
    - libclang==13.0.0
    - markdown==3.3.6
    - numpy==1.19.5
    - oauthlib==3.1.1
    - opt-einsum==3.3.0
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - python-slugify==5.0.2
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - six==1.15.0
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.7.0
    - tensorflow-estimator==2.7.0
    - tensorflow-io-gcs-filesystem==0.23.1
    - termcolor==1.1.0
    - text-unidecode==1.3
    - typing-extensions==3.7.4.3
    - wrapt==1.12.1
