name: tensorflow
channels:
  - conda-forge
dependencies:
  - absl-py=0.10.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - astunparse=1.6.3
  - async_generator=1.10
  - attrs=21.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bleach=4.1.0
  - boto3=1.20.37
  - botocore=1.23.37
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.10
  - click=8.0.3
  - colorama=0.4.4
  - cryptography=36.0.1
  - cycler=0.11.0
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.3
  - flask=2.0.2
  - flit-core=3.6.0
  - fonttools=4.28.5
  - freetype=2.10.4
  - gast=0.4.0
  - google-pasta=0.2.0
  - grpcio=1.34.1
  - h11=0.12.0
  - h5py=3.1.0
  - hdf5=1.10.6
  - icu=69.1
  - idna=3.1
  - importlib-metadata=4.10.0
  - importlib_resources=5.4.0
  - ipykernel=6.7.0
  - ipython=7.31.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - itsdangerous=2.0.1
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.0.3
  - jmespath=0.10.0
  - joblib=1.1.0
  - jpeg=9d
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.1.1
  - jupyter_console=6.4.0
  - jupyter_core=4.9.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.2
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.81.0
  - libcxx=12.0.1
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libiconv=1.16
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libprotobuf=3.19.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp-base=1.2.1
  - libxml2=2.9.12
  - libxslt=1.1.33
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - lxml=4.7.1
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - munkres=1.1.4
  - nb_conda=2.2.1
  - nb_conda_kernels=2.3.1
  - nbclient=0.5.10
  - nbconvert=6.4.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.4
  - notebook=6.4.7
  - numpy=1.19.5
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - opt_einsum=3.3.0
  - outcome=1.1.0
  - packaging=21.3
  - pandas=1.3.5
  - pandas-datareader=0.10.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.3.1
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.24
  - prompt_toolkit=3.0.24
  - protobuf=3.19.3
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=21.0.0
  - pyparsing=3.0.6
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.9
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.3
  - pyyaml=6.0
  - pyzmq=22.3.0
  - readline=8.1
  - requests=2.27.1
  - s3transfer=0.5.0
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - selenium=4.1.0
  - send2trash=1.8.0
  - setuptools=59.8.0
  - six=1.15.0
  - sniffio=1.2.0
  - sortedcontainers=2.4.0
  - sqlite=3.37.0
  - tensorflow=2.5.0
  - termcolor=1.1.0
  - terminado=0.12.1
  - testpath=0.5.0
  - threadpoolctl=3.0.0
  - tk=8.6.11
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.1
  - trio=0.19.0
  - trio-websocket=0.9.2
  - typing_extensions=3.7.4.3
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.2
  - wrapt=1.12.1
  - wsproto=0.14.0
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.1
  - pip:
    - apscheduler==3.8.1
    - bayesian-optimization==1.2.0
    - cachetools==4.2.4
    - cloudpickle==2.0.0
    - flatbuffers==1.12
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - gunicorn==20.1.0
    - gym==0.21.0
    - kaggle==1.5.12
    - keras-nightly==2.5.0.dev2021032900
    - markdown==3.3.6
    - oauthlib==3.1.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - python-slugify==5.0.2
    - pytz-deprecation-shim==0.1.0.post0
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-estimator==2.5.0
    - tensorflow-macos==2.5.0
    - tensorflow-metal==0.1.2
    - text-unidecode==1.3
    - tzdata==2021.5
    - tzlocal==4.1
